name: Continuous Delivery

on:
  push:
    branches:
      - main
      - ci/npm-publish

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: |
          npm ci
          npm run bootstrap

      - name: Continuous Integration
        run: |
          npm run lint
          npm run test
          npm run build

      - name: Continuous Deployment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run version -- --yes
          npm run publish -- --yes
          npm run deploy:storybook -- --ci
