name: Continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install, lint, and test
        run: |
          npm ci
          npm run bootstrap
          npm run lint
          npm run build --if-present --workspaces
          npm run test --if-present --workspaces
